import re
from tune import Tune

gn_dict = {
    "ag": 1,
    "bg": 1,
    "cg": 1,
    "dg": 1,
    "eg": 1,
    "fg": 1,
    "gg": 1,
    "tg": 1,
    "dblg": 2,
    "dbla": 2,
    "dbb": 2,
    "dbc": 2,
    "dbd": 2,
    "dbe": 2,
    "dbf": 2,
    "dbhg": 3,
    "dbha": 2,
    "tdblg": 2,
    "tdbla": 2,
    "tdbb": 2,
    "tdbc": 2,
    "tdbd": 2,
    "tdbe": 2,
    "tdbf": 2,
    "hdblg": 1,
    "hdbla": 1,
    "hdbb": 1,
    "hdbc": 1,
    "hdbd": 1,
    "hdbe": 1,
    "hdbf": 1,
    "strlg": 1,
    "strla": 1,
    "strb": 1,
    "strc": 1,
    "strd": 1,
    "stre": 1,
    "strf": 1,
    "strhg": 1,
    "gstla": 2,
    "gstb": 2,
    "gstc": 2,
    "gstd": 2,
    "lgstd": 2,
    "gste": 2,
    "gstf": 2,
    "tstla": 2,
    "tstb": 2,
    "tstc": 2,
    "tstd": 2,
    "ltstd": 2,
    "tste": 2,
    "tstf": 2,
    "tsthg": 2,
    "hstla": 1,
    "hstb": 1,
    "hstc": 1,
    "hstd": 1,
    "lhstd": 1,
    "hste": 1,
    "hstf": 1,
    "hsthg": 1,
    "grp": 3,
    "hgrip": 2,
    "grpb": 3,
    "ggrpla": 4,
    "ggrpb": 4,
    "ggrpc": 4,
    "ggrpd": 4,
    "ggrpdb": 4,
    "ggrpe": 4,
    "ggrpf": 4,
    "tgrpla": 4,
    "tgrpb": 4,
    "tgrpc": 4,
    "tgrpd": 4,
    "tgrpdb": 4,
    "tgrpe": 4,
    "tgrpf": 4,
    "tgrphg": 4,
    "hgrpla": 4,
    "hgrpb": 4,
    "hgrpc": 4,
    "hgrpd": 4,
    "hgrpdb": 4,
    "hgrpe": 4,
    "hgrpf": 4,
    "hgrphg": 4,
    "hgrpha": 4,
    "tar": 4,
    "tarb": 4,
    "htar": 3,
    "bubly": 3,
    "hbubly": 3,
    "brl": 2,
    "abr": 2,
    "gbr": 3,
    "tbr": 3,
    "thrd": 4,
    "hvthrd": 4,
    "hthrd": 3,
    "hhvthrwd": 3,
    "pella": 3,
    "pelb": 3,
    "pelc": 3,
    "peld": 3,
    "lpeld": 3,
    "pele": 3,
    "pelf": 3,
    "tpella": 3,
    "tpelb": 3,
    "tpelc": 3,
    "tpeld": 3,
    "tlpeld": 3,
    "tpele": 3,
    "tpelf": 3,
    "tpelhg": 3,
    "hpella": 3,
    "hpelb": 3,
    "hpelc": 3,
    "hpeld": 3,
    "hlpeld": 3,
    "hpele": 3,
    "hpelf": 3,
    "hpelhg": 3,
}
gn_counts = {
    "ag": 1,
    "bg": 1,
    "cg": 1,
    "dg": 1,
    "eg": 1,
    "fg": 1,
    "gg": 1,
    "tg": 1,
    "dblg": 3,
    "dbla": 3,
    "dbb": 3,
    "dbc": 3,
    "dbd": 3,
    "dbe": 3,
    "dbf": 3,
    "dbhg": 2,
    "dbha": 2,
    "tdblg": 3,
    "tdbla": 3,
    "tdbb": 3,
    "tdbc": 3,
    "tdbd": 3,
    "tdbe": 3,
    "tdbf": 3,
    "hdblg": 2,
    "hdbla": 2,
    "hdbb": 2,
    "hdbc": 2,
    "hdbd": 2,
    "hdbe": 2,
    "hdbf": 2,
    "strlg": 1,
    "strla": 1,
    "strb": 1,
    "strc": 1,
    "strd": 1,
    "stre": 1,
    "strf": 1,
    "strhg": 1,
    "gstla": 3,
    "gstb": 3,
    "gstc": 3,
    "gstd": 3,
    "lgstd": 3,
    "gste": 3,
    "gstf": 3,
    "tstla": 3,
    "tstb": 3,
    "tstc": 3,
    "tstd": 3,
    "ltstd": 3,
    "tste": 3,
    "tstf": 3,
    "tsthg": 3,
    "hstla": 2,
    "hstb": 2,
    "hstc": 2,
    "hstd": 2,
    "lhstd": 2,
    "hste": 2,
    "hstf": 2,
    "hsthg": 2,
    "grp": 3,
    "hgrip": 2,
    "grpb": 3,
    "ggrpla": 5,
    "ggrpb": 5,
    "ggrpc": 5,
    "ggrpd": 5,
    "ggrpdb": 5,
    "ggrpe": 5,
    "ggrpf": 5,
    "tgrpla": 5,
    "tgrpb": 5,
    "tgrpc": 5,
    "tgrpd": 5,
    "tgrpdb": 5,
    "tgrpe": 5,
    "tgrpf": 5,
    "tgrphg": 5,
    "hgrpla": 4,
    "hgrpb": 4,
    "hgrpc": 4,
    "hgrpd": 4,
    "hgrpdb": 4,
    "hgrpe": 4,
    "hgrpf": 4,
    "hgrphg": 4,
    "hgrpha": 4,
    "tar": 4,
    "tarb": 4,
    "htar": 3,
    "bubly": 5,
    "hbubly": 4,
    "brl": 3,
    "abr": 4,
    "gbr": 5,
    "tbr": 5,
    "thrd": 3,
    "hvthrd": 4,
    "hthrd": 2,
    "hhvthrwd": 3,
    "pella": 5,
    "pelb": 5,
    "pelc": 5,
    "peld": 5,
    "lpeld": 5,
    "pele": 5,
    "pelf": 5,
    "tpella": 5,
    "tpelb": 5,
    "tpelc": 5,
    "tpeld": 5,
    "tlpeld": 5,
    "tpele": 5,
    "tpelf": 5,
    "tpelhg": 5,
    "hpella": 4,
    "hpelb": 4,
    "hpelc": 4,
    "hpeld": 4,
    "hlpeld": 4,
    "hpele": 4,
    "hpelf": 4,
    "hpelhg": 4,
}
note_change_mod = {
    "ag": 1,
    "bg": 1,
    "cg": 1,
    "dg": 1,
    "eg": 1,
    "fg": 1,
    "gg": 1,
    "tg": 1,
    "dblg": 1,
    "dbla": 1,
    "dbb": 1,
    "dbc": 1,
    "dbd": 1,
    "dbe": 1,
    "dbf": 1,
    "dbhg": 1,
    "dbha": 1,
    "tdblg": 1,
    "tdbla": 1,
    "tdbb": 1,
    "tdbc": 1,
    "tdbd": 1,
    "tdbe": 1,
    "tdbf": 1,
    "hdblg": 1,
    "hdbla": 1,
    "hdbb": 1,
    "hdbc": 1,
    "hdbd": 1,
    "hdbe": 1,
    "hdbf": 1,
    "strlg": 1,
    "strla": 1,
    "strb": 1,
    "strc": 1,
    "strd": 1,
    "stre": 1,
    "strf": 1,
    "strhg": 1,
    "gstla": 1,
    "gstb": 1,
    "gstc": 1,
    "gstd": 1,
    "lgstd": 1,
    "gste": 1,
    "gstf": 1,
    "tstla": 1,
    "tstb": 1,
    "tstc": 1,
    "tstd": 1,
    "ltstd": 1,
    "tste": 1,
    "tstf": 1,
    "tsthg": 1,
    "hstla": 1,
    "hstb": 1,
    "hstc": 1,
    "hstd": 1,
    "lhstd": 1,
    "hste": 1,
    "hstf": 1,
    "hsthg": 1,
    "grp": 0,
    "hgrip": 1,
    "grpb": 0,
    "ggrpla": 1,
    "ggrpb": 1,
    "ggrpc": 1,
    "ggrpd": 1,
    "ggrpdb": 1,
    "ggrpe": 1,
    "ggrpf": 1,
    "tgrpla": 1,
    "tgrpb": 1,
    "tgrpc": 1,
    "tgrpd": 1,
    "tgrpdb": 1,
    "tgrpe": 1,
    "tgrpf": 1,
    "tgrphg": 1,  # I STOPPED HERE FOR THE NIGHT
    "hgrpla": 4,
    "hgrpb": 4,
    "hgrpc": 4,
    "hgrpd": 4,
    "hgrpdb": 4,
    "hgrpe": 4,
    "hgrpf": 4,
    "hgrphg": 4,
    "hgrpha": 4,
    "tar": 4,
    "tarb": 4,
    "htar": 3,
    "bubly": 3,
    "hbubly": 3,
    "brl": 2,
    "abr": 2,
    "gbr": 3,
    "tbr": 3,
    "thrd": 4,
    "hvthrd": 4,
    "hthrd": 3,
    "hhvthrwd": 3,
    "pella": 3,
    "pelb": 3,
    "pelc": 3,
    "peld": 3,
    "lpeld": 3,
    "pele": 3,
    "pelf": 3,
    "tpella": 3,
    "tpelb": 3,
    "tpelc": 3,
    "tpeld": 3,
    "tlpeld": 3,
    "tpele": 3,
    "tpelf": 3,
    "tpelhg": 3,
    "hpella": 3,
    "hpelb": 3,
    "hpelc": 3,
    "hpeld": 3,
    "hlpeld": 3,
    "hpele": 3,
    "hpelf": 3,
    "hpelhg": 3,
}


def get_apm(filename, tune):
    with open(filename) as f:
        file = f.read()
    data, measures = file.split("&", maxsplit=1)
    measures = measures.split()
    notes = []
    actions = 0
    gn_count = 0
    for note in measures:
        if note[0].isupper() and note[0] != "I":
            notes.append(re.split("[lr_]", note)[0])
        else:
            actions = actions + gn_dict.get(note, 0)
            gn_count = gn_count + gn_counts.get(note, 0)

    note_changes = 0
    for i in range(len(notes) - 1):
        if notes[i] != notes[i + 1]:
            note_changes = note_changes + 1
            actions = actions + 1

    actions = actions * (int(tune.repeats) + 1)
    apm = actions / tune.duration
    apb = actions / tune.num_beats
    density = gn_count / tune.num_beats
    total_notes = note_changes + gn_count
    print(
        f"{tune.title}, {tune.num_parts} parts at {tune.tempo} BPM: {actions} actions."
    )
    print(
        f"{tune.title}, {tune.num_parts} parts at {tune.tempo} BPM: {apm} Actions Per Minute (APM)."
    )
    print(
        f"{tune.title} includes {total_notes} total notes with a grace note density of {density} grace notes per beat."
    )
    # print(f"{tune.title}, {tune.num_parts} parts: {apb} Actions Per Beat (APB).")


"""LAK = Tune("Lord Alexander Kennedy", "2/4 March", 81, 6)
get_apm("LAK.txt", LAK)
STB = Tune("Scotland the Brave", "4/4 March", 90, 2)
get_apm("STB.txt", STB)"""

Susan = Tune("Susan MacLeod", "Strathspey", 120, 4)
get_apm("Susan_Macleod.txt", Susan)
captain = Tune("Captain Horne and Molly Connell", "Strathspey", 120, 4)
get_apm("captain_molly.txt", captain)
